version: "3.7"
services:

    mysql:
        image: mysql:5.7
        container_name: lab-mysql
        working_dir: /application
        command: --init-file /application/db/db.sql --character-set-server=${MYSQL_CHARSET} --collation-server=utf8_general_ci --max_allowed_packet=1000000000 --net_buffer_length=1000000000 --innodb_use_native_aio=0
        volumes:
            - ./db:/application/db
            - ./docker/lab-mysql/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8082:3306"
    
    webserver:
        build: 
            context: ./docker/lab-webserver/
            args: 
                - DEBUG=${DEBUG}
                - XDEBUG_HOST=${XDEBUG_HOST}
        container_name: lab-webserver
        hostname: lab-webserver
        
        environment:
            # Configuracao do banco de dados
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_CHARSET=${MYSQL_CHARSET}

            # Configuracao SMTP
            - EMAIL_USERNAME=${EMAIL_USERNAME}
            - EMAIL_PASSWORD=${EMAIL_PASSWORD}
            - EMAIL_CHARSET=${EMAIL_CHARSET}
            - EMAIL_PORTA=${EMAIL_PORTA}
            - EMAIL_CRIPTOGRAFIA=${EMAIL_CRIPTOGRAFIA}
            - SMTP_HOST=${SMTP_HOST}
        volumes:
            - ./src:/var/www/html/lab
            - ./docker/lab-webserver/facialRecognitionLogin:/home/html/facialRecognitionLogin
            - ./docker/lab-webserver/logs:/var/log/apache2
        ports:
            - "80:80"
        depends_on:
            - mysql
        links:
            - mysql

    deepspeech:
        build: 
            context: ./docker/lab-deepspeech/
        container_name: lab-deepspeech
        hostname: lab-deepspeech
        
        volumes:
            - ./docker/lab-deepspeech/audio:/audio
            - ./docker/lab-deepspeech/logs:/logs
        ports:
            - "8001:80"
        depends_on:
            - mysql
        links:
            - mysql

    smtp:
        image: gessnerfl/fake-smtp-server
        container_name: lab-smtp
        working_dir: /application
        volumes:
            - ./smtp:/application
        ports:
            - "5080:5080"
            - "5081:5081"
