###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
        image: mysql:5.7
        container_name: lab-mysql
        working_dir: /application
        command: --init-file /application/db/db.sql --character-set-server=utf8 --collation-server=utf8_general_ci
        volumes:
            - .:/application
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=<senha_root>
            - MYSQL_DATABASE=lab2
            - MYSQL_USER=lab2
            - MYSQL_PASSWORD=<senha_lab2>
        ports:
            - "8082:3306"

    webserver:
        image: nginx:alpine
        container_name: lab-webserver
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - mysql
            - smtp
        links:
            - mysql
            - smtp

    php-fpm:
        build: phpdocker/php-fpm
        container_name: lab-php-fpm
        working_dir: /application
        volumes:
            - .:/application
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        depends_on:
            - mysql
            - smtp
        links:
            - mysql
            - smtp

    smtp:
        image: gessnerfl/fake-smtp-server
        container_name: lab-smtp
        working_dir: /application
        volumes:
            - ./smtp:/application
        ports:
            - "5080:5080"
            - "5081:5081"
